micronaut:
  application:
    name: productsService

grpc:
  server:
    port: 50052
  channels:
    productservice:
      target: localhost:50052
      plaintext: true

datasources:
  default:
    url: jdbc:h2:mem:devTest;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

flyway:
  datasources:
    default:
      enabled: true
